import image from '../../assets/images/Home/1.jpg'

const state = {
  instructors: [
    {
      id: 1,
      slug: 'muhammad_qasim',
      instructor: 'Muhammad Qasim',
      experience: 6,
      instructor_img: image,
      designation: 'Web Designer',
      address: 'Canada',
      points: 112,
      videos: 87,
      lectures: 120,
      classes: [
        {
          id: 1,
          link: image,
          title: 'Start Learning Web Designing',
          total_lessons: 20,
          chapter_name: 'Designing',
        },
        {
          id: 2,
          link: image,
          title: 'Start Learning Business Designing',
          total_lessons: 22,
          chapter_name: 'Designing',
        },
        {
          id: 3,
          link: image,
          title: 'Start Learning Award Designing Start Learning Award Designing Start Learning Award Designing',
          total_lessons: 13,
          chapter_name: 'Designing',
        },
        {
          id: 4,
          link: image,
          title: 'Start Learning MBA Designing',
          total_lessons: 19,
          chapter_name: 'Learning',
        },
        {
          id: 5,
          link: image,
          title: 'Start Show Designing',
          total_lessons: 13,
          chapter_name: 'Designing',
        },
        {
          id: 6,
          link: image,
          title: 'Start Switch Designing Start Switch Designing Start Switch Designing',
          total_lessons: 19,
          chapter_name: 'Designing',
        },
      ],
      education: [
        {
          id: 1,
          degree: 'Master In Fine Art',
          duratioin: '2017 - 2019',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 2,
          degree: 'Tombia Collage',
          duratioin: '2015 - 2017',
          institution: 'Wikked Collage',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 3,
          degree: 'Diploma In Fine Art',
          duratioin: '20012 - 2015',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        }
      ],
    },

    {
      id: 2,
      slug: 'abdul_kuddus',
      instructor: 'Abdul Kuddus',
      experience: 10,
      instructor_img: image,
      designation: 'Marketing Manager',
      address: 'Australia',
      points: 103,
      videos: 12,
      lectures: 27,
      classes: [
        {
          id: 1,
          link: image,
          title: 'Start Learning Mobile Designing',
          total_lessons: 14,
          chapter_name: 'Designing',
        },
        {
          id: 2,
          link: image,
          title: 'Start Learning Company Designing',
          total_lessons: 13,
          chapter_name: 'Designing',
        },
        {
          id: 3,
          link: image,
          title: 'Start Learning Award Pro Designing',
          total_lessons: 11,
          chapter_name: 'Designing',
        },
        {
          id: 4,
          link: image,
          title: 'Start Learning BBA Designing',
          total_lessons: 10,
          chapter_name: 'Designing',
        },
        {
          id: 5,
          link: image,
          title: 'Start Learning Award Pro Designing',
          total_lessons: 11,
          chapter_name: 'Designing',
        },
        {
          id: 6,
          link: image,
          title: 'Start Learning BBA Designing',
          total_lessons: 10,
          chapter_name: 'Designing',
        },
      ],
      education: [
        {
          id: 1,
          degree: 'Master In Finance',
          duratioin: '2017 - 2019',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 2,
          degree: 'Tombia Collage',
          duratioin: '2015 - 2020',
          institution: 'Wikked Collage',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 3,
          degree: 'Diploma In Fine Art',
          duratioin: '20012 - 2015',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        }
      ],
    },
    {
      id: 3,
      slug: 'abdus_salam',
      instructor: 'Abdus Salam',
      experience: 9,
      instructor_img: image,
      designation: 'UX Designer',
      address: 'Japan',
      points: 100,
      videos: 20,
      lectures: 120,
      classes: [
        {
          id: 1,
          link: image,
          title: 'Start Mobile app Designing',
          total_lessons: 12,
          chapter_name: 'Designing',
        },
        {
          id: 2,
          link: image,
          title: 'Start Learning Business Designing',
          total_lessons: 11,
          chapter_name: 'Designing',
        },
        {
          id: 3,
          link: image,
          title: 'Start Learning Award Designing',
          total_lessons: 10,
          chapter_name: 'Designing',
        },
        {
          id: 4,
          link: image,
          title: 'Start Learning MBA Designing',
          total_lessons: 9,
          chapter_name: 'Designing',
        },
        {
          id: 5,
          link: image,
          title: 'Start Learning Award Designing',
          total_lessons: 8,
          chapter_name: 'Designing',
        },
        {
          id: 6,
          link: image,
          title: 'Start Learning MBA Designing',
          total_lessons: 7,
          chapter_name: 'Designing',
        }
      ],
      education: [
        {
          id: 1,
          degree: 'Master In Fine Art',
          duratioin: '2017 - 2019',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 2,
          degree: 'Tombia Collage',
          duratioin: '2015 - 2017',
          institution: 'Wikked Collage',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 3,
          degree: 'Diploma In Fine Art',
          duratioin: '20012 - 2015',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        }
      ],
    },
    
    {
      id: 4,
      slug: 'sultan_fateh',
      instructor: 'Sultan Fateh',
      experience: 3,
      instructor_img: image,
      designation: 'Web Designer',
      address: 'Canada',
      points: 10,
      videos: 13,
      lectures: 12,
      classes: [
        {
          id: 1,
          link: image,
          title: 'Start Learning Web Designing',
          total_lessons: 12,
          chapter_name: 'Designing',
        },
        {
          id: 2,
          link: image,
          title: 'Start Learning Business Designing',
          total_lessons: 13,
          chapter_name: 'Designing',
        },
        {
          id: 3,
          link: image,
          title: 'Start Learning Award Designing',
          total_lessons: 14,
          chapter_name: 'Designing',
        },
        {
          id: 4,
          link: image,
          title: 'Start Learning MBA Designing',
          total_lessons: 15,
          chapter_name: 'Designing',
        },
        {
          id: 5,
          link: image,
          title: 'Start Learning Award Designing',
          total_lessons: 16,
          chapter_name: 'Designing',
        },
        {
          id: 6,
          link: image,
          title: 'Start Learning MBA Designing',
          total_lessons: 17,
          chapter_name: 'Designing',
        },
      ],
      education: [
        {
          id: 1,
          degree: 'Master In Fine Art',
          duratioin: '2017 - 2019',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 2,
          degree: 'Tombia Collage',
          duratioin: '2015 - 2017',
          institution: 'Wikked Collage',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 3,
          degree: 'Diploma In Fine Art',
          duratioin: '20012 - 2015',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        }
      ],
    },

    {
      id: 5,
      slug: 'hasanur_rahman',
      instructor: 'Hasanur Rahman',
      experience: 6,
      instructor_img: image,
      designation: 'Web Designer',
      address: 'Canada',
      points: 112,
      videos: 87,
      lectures: 120,
      classes: [
        {
          id: 1,
          link: image,
          title: 'Start Learning Web Designing',
          total_lessons: 20,
          chapter_name: 'Designing',
        },
        {
          id: 2,
          link: image,
          title: 'Start Learning Business Designing',
          total_lessons: 22,
          chapter_name: 'Designing',
        },
        {
          id: 3,
          link: image,
          title: 'Start Learning Award Designing Start Learning Award Designing Start Learning Award Designing',
          total_lessons: 13,
          chapter_name: 'Designing',
        },
        {
          id: 4,
          link: image,
          title: 'Start Learning MBA Designing',
          total_lessons: 19,
          chapter_name: 'Learning',
        },
        {
          id: 5,
          link: image,
          title: 'Start Show Designing',
          total_lessons: 13,
          chapter_name: 'Designing',
        },
        {
          id: 6,
          link: image,
          title: 'Start Switch Designing Start Switch Designing Start Switch Designing',
          total_lessons: 19,
          chapter_name: 'Designing',
        },
      ],
      education: [
        {
          id: 1,
          degree: 'Master In Fine Art',
          duratioin: '2017 - 2019',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 2,
          degree: 'Tombia Collage',
          duratioin: '2015 - 2017',
          institution: 'Wikked Collage',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 3,
          degree: 'Diploma In Fine Art',
          duratioin: '20012 - 2015',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        }
      ],
    },

    {
      id: 6,
      slug: 'robert_brown',
      instructor: 'Robert Brown',
      experience: 6,
      instructor_img: image,
      designation: 'Web Designer',
      address: 'Canada',
      points: 112,
      videos: 87,
      lectures: 120,
      classes: [
        {
          id: 1,
          link: image,
          title: 'Start Learning Web Designing',
          total_lessons: 20,
          chapter_name: 'Designing',
        },
        {
          id: 2,
          link: image,
          title: 'Start Learning Business Designing',
          total_lessons: 22,
          chapter_name: 'Designing',
        },
        {
          id: 3,
          link: image,
          title: 'Start Learning Award Designing Start Learning Award Designing Start Learning Award Designing',
          total_lessons: 13,
          chapter_name: 'Designing',
        },
        {
          id: 4,
          link: image,
          title: 'Start Learning MBA Designing',
          total_lessons: 19,
          chapter_name: 'Learning',
        },
        {
          id: 5,
          link: image,
          title: 'Start Show Designing',
          total_lessons: 13,
          chapter_name: 'Designing',
        },
        {
          id: 6,
          link: image,
          title: 'Start Switch Designing Start Switch Designing Start Switch Designing',
          total_lessons: 19,
          chapter_name: 'Designing',
        },
      ],
      education: [
        {
          id: 1,
          degree: 'Master In Fine Art',
          duratioin: '2017 - 2019',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 2,
          degree: 'Tombia Collage',
          duratioin: '2015 - 2017',
          institution: 'Wikked Collage',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        },
        {
          id: 3,
          degree: 'Diploma In Fine Art',
          duratioin: '20012 - 2015',
          institution: 'Meeruth University',
          details: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        }
      ],
    },
  ]
}

const getters = {

}

export default {
  namespaced: true,
  state,
  getters
}